version: "3.8"


services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
#      - dev-static-data:/app/staticfiles
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py collectstatic --noinput &&
              python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=ariakon.postgres.database.azure.com
      - DB_NAME=ariakon_db
      - DB_USER=ariakon_user
      - DB_PASS=admin@321
      - NUMBA_CACHE_DIR=/nonexistent_path
    depends_on:
      - db

  db:
    image: postgres:16.3-alpine3.20
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=Ariakon
      - POSTGRES_USER=ariakon_user
      - POSTGRES_PASSWORD=admin@321
      - DEBUG=1

  format:
    build:
      context: .
      args:
        - DEV=false
    volumes:
      - ./app:/app
    command: >
      sh -c "/py/bin/black /app"
    depends_on:
      - app

volumes:
  dev-db-data:
  dev-static-data: