# Generated by Django 5.1.2 on 2024-11-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiofile",
            name="unit",
            field=models.CharField(
                choices=[("inches", "In"), ("meters", "M"), ("centimeters", "CM")],
                default="inches",
                max_length=20,
            ),
        ),
    ]
