---
name: Checks

on: [push] # Trigger

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.3-alpine3.20
        env:
          POSTGRES_DB: devdb
          POSTGRES_USER: devuser
          POSTGRES_PASSWORD: changeme
        ports:
          - 5432:5432
        volumes:
          - dev-db-data:/var/lib/postgresql/data

    steps:
      - name: Install Docker Compose
        run: |
            sudo apt-get update
            sudo apt-get install -y docker-compose

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker-compose build --build-arg DEV=true

      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"

      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Test
        run: docker-compose up --abort-on-container-exit --exit-code-from test

